[build-system]
requires = ["setuptools>=45", "setuptools_scm[toml]>=6.2", "setuptools-git-versioning",]
build-backend = "setuptools.build_meta"

[project]
name = "smbcrawler"
dynamic = ["version"]
authors = [
    {name = "Adrian Vollmer", email = "adrian.vollmer@syss.de"},
]
description = 'Search SMB shares for interesting files'
readme = "README.md"
requires-python = ">=3.8"
keywords = ["pentest", "smb", "shares", "reconnaissance"]
license = {text = "MIT License"}
classifiers = [
    "Operating System :: POSIX :: Linux",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
]
dependencies = [
    'impacket>=0.9.20',
    'python-libnmap',
    'lxml',
    'pdftotext',
    'python-magic',
    'json2html',
]

[tool.setuptools]
packages = ["smbcrawler"]

[tool.setuptools-git-versioning]
enabled = true

[project.urls]
"Homepage" = 'https://github.com/SySS-Research/smbcrawler'
"Bug Tracker" = 'https://github.com/SySS-Research/smbcrawler/issues'

[project.scripts]
smbcrawler = "smbcrawler.__main__:main"

[project.optional-dependencies]
tests = [
  'pytest',
  'pyexpect',
  'tox',
]

[tool.pytest.ini_options]
norecursedirs = tests/helpers
filterwarnings = ignore::DeprecationWarning

[tool.tox]
legacy_tox_ini = """
[tox]
envlist = py37,py39,lint

[testenv]
basepython =
    {lint}: {env:TOXPYTHON:python3}
    py39: {env:TOXPYTHON:python3.9}
passenv = *
install_command = pip install {opts} {packages}
deps =
    pytest
usedevelop = false
commands = pytest -W ignore::DeprecationWarning -v {posargs} tests

[testenv:lint]
skip_install = true
deps = flake8
commands = flake8
"""
